### ISSUE TITLE
Does this not install fpc?

### ISSUE THREAD

**Issue by jaredsburrows** [suve/GHActions-FPC#6]
## Description:
Does this not install the `fpc` binary? If not, can you update the `README.md` description?

## Error:
```
Run suve/GHActions-FPC@v0.4.0
  with:
    fail-on: e
    user-defined: *
    verbosity: ew
  env:
    CLOJURE_INSTALL_DIR: /tmp/usr/local/opt/ClojureTools
    DC: dmd
    LD_LIBRARY_PATH: /opt/hostedtoolcache/dc/dmd-2.102.2/x64/dmd2/linux/lib64
    PUB_CACHE: /home/runner/.pub-cache
    DART_HOME: /opt/hostedtoolcache/dart-sdk
    INSTALL_DIR_FOR_OTP: /home/runner/work/_temp/.setup-beam/otp
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
    JAVA_HOME_19_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
    OPAMCLI: 2.0
    OPAMCOLOR: always
    OPAMERRLOGLEN: 0
    OPAMJOBS: 2
    OPAMPRECISETRACKING: 1
    OPAMSOLVERTIMEOUT: 1000
    OPAMVERBOSE: false
    OPAMYES: 1
    CLICOLOR_FORCE: 1
Error: Unable to locate executable file: fpc. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by suve** [comment]
This does not install FPC for you, and the README already mentions that (along with instructions on how to do it yourself).

**Comment by jaredsburrows** [comment]
@suve Thanks. I see it here now: https://github.com/suve/GHActions-FPC#getting-fpc. Consider adding that in the future? :)

**Comment by suve** [comment]
This could be done, but the main problem is that it'd be hard to make it reliable. While GHActions have built-in runners for Ubuntu, MacOS and Windows, users are free to run their jobs in a container, which can contain any Linux distro under the sun... which means it can be equipped with any of the bazillion package managers out there.
